//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public Device()
        {
            this.DeviceHouse = new HashSet<DeviceHouse>();
            this.Error = new HashSet<Error>();
            this.NetworkStatus = new HashSet<NetworkStatus>();
            this.SensorDry = new HashSet<SensorDry>();
        }
    
        public int Id { get; set; }
        public string IpAddress { get; set; }
        public string Password { get; set; }
        public string SerialNumber { get; set; }
        public string FirmwareVersion { get; set; }
        public string MacAddress { get; set; }
        public int Model { get; set; }
    
        public virtual DeviceModel DeviceModel { get; set; }
        public virtual ICollection<DeviceHouse> DeviceHouse { get; set; }
        public virtual ICollection<Error> Error { get; set; }
        public virtual ICollection<NetworkStatus> NetworkStatus { get; set; }
        public virtual ICollection<SensorDry> SensorDry { get; set; }
    }
}
