//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KModel.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KBaseEntities : DbContext
    {
        public KBaseEntities()
            : base("name=KBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<AspNetRoles> AspNetRoles { get; set; }
        public DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public DbSet<AspNetUsers> AspNetUsers { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<Device> Device { get; set; }
        public DbSet<DeviceHouse> DeviceHouse { get; set; }
        public DbSet<DeviceModel> DeviceModel { get; set; }
        public DbSet<Door> Door { get; set; }
        public DbSet<Error> Error { get; set; }
        public DbSet<House> House { get; set; }
        public DbSet<HouseUser> HouseUser { get; set; }
        public DbSet<NetworkStatus> NetworkStatus { get; set; }
        public DbSet<Org> Org { get; set; }
        public DbSet<Premises> Premises { get; set; }
        public DbSet<ReasonForDisarming> ReasonForDisarming { get; set; }
        public DbSet<Region> Region { get; set; }
        public DbSet<Report> Report { get; set; }
        public DbSet<SensorDry> SensorDry { get; set; }
        public DbSet<SensorDryData> SensorDryData { get; set; }
        public DbSet<SensorDryType> SensorDryType { get; set; }
        public DbSet<SensorDryValueType> SensorDryValueType { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
