//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Org
    {
        public Org()
        {
            this.AspNetUsers = new HashSet<AspNetUsers>();
            this.House = new HashSet<House>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string LegalAddress { get; set; }
        public string PostalAddress { get; set; }
        public string Inn { get; set; }
        public string Kpp { get; set; }
        public int Region { get; set; }
        public int City { get; set; }
    
        public virtual ICollection<AspNetUsers> AspNetUsers { get; set; }
        public virtual City City1 { get; set; }
        public virtual ICollection<House> House { get; set; }
        public virtual Region Region1 { get; set; }
    }
}
