//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorDryValueType
    {
        public SensorDryValueType()
        {
            this.SensorDryType = new HashSet<SensorDryType>();
        }
    
        public int Id { get; set; }
        public string Value0 { get; set; }
        public string Value1 { get; set; }
        public string SecurityStatus0 { get; set; }
        public string SecurityStatus1 { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<SensorDryType> SensorDryType { get; set; }
    }
}
